### ISSUE TITLE
Plugin activation issue

### ISSUE THREAD

**Issue by Raja1805** [prokerala/wp-astrology#2]
I get the below error during plugin activation. In astrology.php, I see at line no 99, its trying to load /src/vendor/autoload.php. But I dont see that file in source code at all.

Warning: require_once(../wp-content/plugins/wp-astrology-master/src/vendor/autoload.php): failed to open stream: No such file or directory in ..wp-content/plugins/wp-astrology-master/astrology.php on line 99

Fatal error: require_once(): Failed opening required '..wp-content/plugins/wp-astrology-master/src/vendor/autoload.php' (include_path='.:/opt/alt/php73/usr/share/pear') in ../wp-content/plugins/wp-astrology-master/astrology.php on line 99

**Comment by JoyceBabu** [comment]
You should download and use the release package from

https://github.com/prokerala/wp-astrology/releases

**Comment by Raja1805** [comment]
I have downloaded latest astrology.zip and it got installed fine. I dont see any documentation on how to use the plugin in the site.

**Comment by JoyceBabu** [comment]
The plugin ads a new block named 'Astrology Report' to the Gutenberg block editor.

Alternatively, you can use the short code `[astrology report="REPORT_NAME"]`, where report name is any of the [supported reports](https://github.com/prokerala/wp-astrology/tree/master/src/Front/Report). For example, for panchang report use

```
[astrology report="Panchang"]
```
